version: 0.2

env:
  variables:
    AWS_REGION: us-west-2
    ECR_REGISTRY: 604956611121.dkr.ecr.us-west-2.amazonaws.com
    REPOSITORY_NAME: javatechie-registry

phases:
  pre_build:
    commands:
      - export REPOSITORY_URI=$ECR_REGISTRY/$REPOSITORY_NAME
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - mvn clean install
      - docker build -t $REPOSITORY_URI .

  post_build:
    commands:
      - docker push $REPOSITORY_URI

artifacts:
  files:
    - '**/*'
